name: tcvc
channels:
- pytorch
- defaults
dependencies:
- imageio>=2.4,<=2.5
- matplotlib=3.0
- mkl
- numpy>=1.13,<2
- pip>=10,<=19.1.1
- python=3.6.6
- scikit-image>=0.14,<1
- scipy>=1.0,<1.2
- pytorch=0.4.1
- pip:
  - black
  - hasel
  - Keras==2.2
  - opencv-python==3.4.1.15
  - Pillow>=5.1,<=6
  - pytest==4.6
  - pytest-cov==2.7.1
  - tensorflow-gpu==1.11
  - torchvision==0.2
  - tqdm
