name: tcvc
channels:
- pytorch
- defaults
dependencies:
- matplotlib=3.0
- mkl
- numpy>=1.13,<2
- pip>=10,<=19.1.1
- python=3.5.5
- scikit-image>=0.14,<1
- scipy>=1.0,<2
- pytorch=0.4.1
- pip:
  - Pillow>=5.1,<=6
  - pytest==4.6
  - pytest-cov==2.7.1
  - torchvision==0.2
  - tqdm
